/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saúde do serviço */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica e devolve o par de tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotaciona o par de tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerra a sessão, revogando o refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário atual e suas permissões efetivas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            username: string;
                            /** Format: uuid */
                            roleId: string | null;
                            permissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Troca a própria senha */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        currentPassword: string;
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os papéis */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            permissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Cria um papel */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        permissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            permissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove o papel; seus usuários ficam sem herança */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Edita o nome e o pacote de permissões */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        permissions?: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            permissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os usuários */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            username: string;
                            /** Format: uuid */
                            roleId: string | null;
                            extraPermissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                            permissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                            isActive: boolean;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Cria um usuário */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        username: string;
                        password: string;
                        /** Format: uuid */
                        roleId?: string | null;
                        extraPermissions?: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            username: string;
                            /** Format: uuid */
                            roleId: string | null;
                            extraPermissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                            permissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                            isActive: boolean;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cadastro e permissões efetivas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            username: string;
                            /** Format: uuid */
                            roleId: string | null;
                            extraPermissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                            permissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                            isActive: boolean;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edita papel, permissões avulsas, nome e situação */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        /** Format: uuid */
                        roleId?: string | null;
                        extraPermissions?: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                        isActive?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            username: string;
                            /** Format: uuid */
                            roleId: string | null;
                            extraPermissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                            permissions: ("CATALOG_READ" | "CATALOG_CREATE" | "CATALOG_UPDATE" | "ENTRIES_READ" | "ENTRIES_CREATE" | "PRODUCTION_READ" | "PRODUCTION_CREATE" | "SALES_READ" | "SALES_CREATE" | "REPORTS_READ" | "ACCESS_READ" | "ACCESS_CREATE" | "ACCESS_UPDATE")[];
                            isActive: boolean;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reseta a senha de outro usuário */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
